server {
    listen 4800;

    client_header_buffer_size 64k;
    large_client_header_buffers 4 64k;

    location /erp/panel/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /erp/console/index.html;
    }
}